### PR TITLE
Testing setup

### PR DESCRIPTION
**Pull request by larsonme**
This Pull Request contains the webdriverio configuration file along with the folders needed for the results from the tests.

### CODE REVIEW

**Comment by StrikeNP** [comment]
Looks good, little room for issues.

**Review by StrikeNP — APPROVED** [review]
Looks good, just files added with a couple lines in config.

**Comment by murphyad** [comment]
Added files do not conflict with existing code, are documented and styled properly.

**Comment by DonalMoloneyMSOE** [comment]
ok its cool

**Comment by DonalMoloneyMSOE** [comment]
Looks thorough

**Pull request merged**
