### PR TITLE
Added documentation

### PR DESCRIPTION
**Pull request by fontainesw**

### CODE REVIEW

**Comment by ConnorHibbs** [comment]
Could you include a PDF as well?

Steven-"I personally don't like the Idea of adding a PDF as it creates a static document which is an extra step in the generation process, which may result in letting it become stale. Not all PDF printers are capable of maintaining self referencing links, as well, which reduces functionality. Also, it separates a smooth document into pages, which is gross. I however have included a PDF at your request"

**Comment by Lou3797** [comment]
Could you add your GraphQL Confluence page to this PR as well? It looks like a great page that would be valuable to have offline.

Steven-"I had wanted confluence to be the source of truth for this project, but I have included the PDF as requested"

**Review by ConnorHibbs — APPROVED** [review]
Thanks for making that documentation into a PDF! I think it's just a little more portable that way. :100:

**Review by Lou3797 — APPROVED** [review]
I must agree with Connor that the PDF will just be convenient for the next team to have. Thanks and good job!

**Pull request merged**
